name: Run Telegram Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types: [start_bot]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualizar a v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Actualizar a v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Info
        run: |
          python --version
          pip --version
          pip list

      - name: Run bot
        run: |
          python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
